spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WebEnglish
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:postgresql://ep-sweet-breeze-a8346i6g-pooler.eastus2.azure.neon.tech/web_english?sslmode=require
#    username: web_english_owner
#    password: npg_5dMhjAPNgJw4
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  main:
    allow-circular-references: true